apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-app
  name: spring-boot-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-app
  type: LoadBalancer