apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
  name: eureka-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka-server
  type: LoadBalancer