apiVersion: v1
kind: Service
metadata:
  name: my-spring-boot-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-spring-boot-app
  type: LoadBalancer