apiVersion: v1
kind: Service
metadata:
  labels:
    app: id-generator
  name: id-generator-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: id-generator
  type: LoadBalancer