apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-user-tenant-orm
  name: multi-user-tenant-orm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-user-tenant-orm
  template:
    metadata:
      labels:
        app: multi-user-tenant-orm
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: <your-docker-registry>/multi-user-tenant-orm:latest
        name: multi-user-tenant-orm
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi