apiVersion: v1
kind: Service
metadata:
  labels:
    app: multi-user-tenant-orm
  name: multi-user-tenant-orm-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: multi-user-tenant-orm
  type: LoadBalancer