apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: <your-docker-registry>/eureka-server:latest #Replace with your docker image
        ports:
        - containerPort: 8761 # Default Eureka port
        # Add livenessProbe and readinessProbe if your application exposes health endpoints
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8761
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8761
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://localhost:8761/eureka/ #Placeholder for external Eureka instance if needed.  Adjust accordingly. 
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi