apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-activemq-app
  name: spring-activemq-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-activemq-app
  template:
    metadata:
      labels:
        app: spring-activemq-app
    spec:
      containers:
      - env:
        - name: SPRING_ACTIVEMQ_BROKER_URL
          value: tcp://activemq-service:61616
        image: io.platformconsulting/spring-activemq-app:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        name: spring-activemq-app-container
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi