apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-import
  name: data-import
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-import
  template:
    metadata:
      labels:
        app: data-import
    spec:
      containers:
      - env: null
        image: com.emc.data/data-import:latest
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
