apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-import
  name: data-import-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: data-import
  type: LoadBalancer