apiVersion: v1
kind: Service
metadata:
  labels:
    app: live-data-ingestion
  name: live-data-ingestion-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: live-data-ingestion
  type: LoadBalancer