apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-xd-elasticsearch-sink
  name: spring-xd-elasticsearch-sink
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-xd-elasticsearch-sink
  type: LoadBalancer